
import { Promoter, Activity, ActivityStatus, ProblemType, UserRole, ActivityType } from '../types';

const defaultLocation = { lat: 13.6929, lng: -89.2182, address: 'San Salvador, El Salvador' };

export const MOCK_PROMOTERS: Promoter[] = [
  {
    id: 'admin-1',
    name: 'Ricardo González',
    username: 'ricardo.gonzalez',
    photo: 'https://picsum.photos/seed/ricardo/200/200',
    email: 'ricardo.gonzalez@promoterflow.com',
    password: 'password123',
    phone: '+503 2200 0001',
    position: 'Administrador General',
    status: 'active',
    isOnline: true,
    lastLocation: defaultLocation,
    lastUpdated: new Date().toISOString(),
    lastConnection: new Date().toISOString(),
    zone: 'Sede Central',
    role: UserRole.ADMIN,
    mustChangePassword: false
  },
  {
    id: 'g-1',
    name: 'Felipe Aguillón',
    username: 'felipe.aguillon',
    photo: 'https://picsum.photos/seed/felipe/200/200',
    email: 'felipe.aguillon@promoterflow.com',
    password: 'password123',
    phone: '+503 7000 0001',
    position: 'Gestor de Campo',
    status: 'active',
    isOnline: false,
    lastLocation: defaultLocation,
    lastUpdated: new Date().toISOString(),
    lastConnection: new Date().toISOString(),
    zone: 'Zona 1',
    role: UserRole.FIELD_PROMOTER,
    mustChangePassword: true
  },
  {
    id: 'g-2',
    name: 'Josseline Argueta',
    username: 'josseline.argueta',
    photo: 'https://picsum.photos/seed/josseline/200/200',
    email: 'josseline.argueta@promoterflow.com',
    password: 'password123',
    phone: '+503 7000 0002',
    position: 'Gestor de Campo',
    status: 'active',
    isOnline: false,
    lastLocation: defaultLocation,
    lastUpdated: new Date().toISOString(),
    lastConnection: new Date().toISOString(),
    zone: 'Zona 2',
    role: UserRole.FIELD_PROMOTER,
    mustChangePassword: true
  },
  {
    id: 'g-3',
    name: 'Samantha Chávez',
    username: 'samantha.chavez',
    photo: 'https://picsum.photos/seed/samantha/200/200',
    email: 'samantha.chavez@promoterflow.com',
    password: 'password123',
    phone: '+503 7000 0003',
    position: 'Gestor de Campo',
    status: 'active',
    isOnline: false,
    lastLocation: defaultLocation,
    lastUpdated: new Date().toISOString(),
    lastConnection: new Date().toISOString(),
    zone: 'Zona 3',
    role: UserRole.FIELD_PROMOTER,
    mustChangePassword: true
  },
  {
    id: 'g-4',
    name: 'Janira Alvarado',
    username: 'janira.alvarado',
    photo: 'https://picsum.photos/seed/janira/200/200',
    email: 'janira.alvarado@promoterflow.com',
    password: 'password123',
    phone: '+503 7000 0004',
    position: 'Gestor de Campo',
    status: 'active',
    isOnline: false,
    lastLocation: defaultLocation,
    lastUpdated: new Date().toISOString(),
    lastConnection: new Date().toISOString(),
    zone: 'Zona 4',
    role: UserRole.FIELD_PROMOTER,
    mustChangePassword: true
  },
  {
    id: 'g-5',
    name: 'Dolores Hernández',
    username: 'dolores.hernandez',
    photo: 'https://picsum.photos/seed/dolores/200/200',
    email: 'dolores.hernandez@promoterflow.com',
    password: 'password123',
    phone: '+503 7000 0005',
    position: 'Gestor de Campo',
    status: 'active',
    isOnline: false,
    lastLocation: defaultLocation,
    lastUpdated: new Date().toISOString(),
    lastConnection: new Date().toISOString(),
    zone: 'Zona 5',
    role: UserRole.FIELD_PROMOTER,
    mustChangePassword: true
  },
  {
    id: 'g-6',
    name: 'Silvia Molina',
    username: 'silvia.molina',
    photo: 'https://picsum.photos/seed/silvia/200/200',
    email: 'silvia.molina@promoterflow.com',
    password: 'password123',
    phone: '+503 7000 0006',
    position: 'Gestor de Campo',
    status: 'active',
    isOnline: false,
    lastLocation: defaultLocation,
    lastUpdated: new Date().toISOString(),
    lastConnection: new Date().toISOString(),
    zone: 'Zona 6',
    role: UserRole.FIELD_PROMOTER,
    mustChangePassword: true
  },
  {
    id: 'g-7',
    name: 'Nohemy de Paz',
    username: 'nohemy.depaz',
    photo: 'https://picsum.photos/seed/nohemy/200/200',
    email: 'nohemy.depaz@promoterflow.com',
    password: 'password123',
    phone: '+503 7000 0007',
    position: 'Gestor de Campo',
    status: 'active',
    isOnline: false,
    lastLocation: defaultLocation,
    lastUpdated: new Date().toISOString(),
    lastConnection: new Date().toISOString(),
    zone: 'Zona 7',
    role: UserRole.FIELD_PROMOTER,
    mustChangePassword: true
  }
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    promoterId: 'g-1',
    date: new Date().toISOString().split('T')[0],
    time: '09:00',
    community: 'Barrio Santa Anita',
    objective: 'Visita de diagnóstico inicial',
    attendeeName: 'Maria Lopez',
    attendeeRole: 'Presidenta ADESCO',
    attendeePhone: '555-0102',
    proposals: 'Mantenimiento de luminarias en calle principal.',
    problemsIdentified: ProblemType.LUMINARIAS,
    agreements: 'Se enviará reporte técnico a mantenimiento.',
    additionalObservations: 'Zona de alto tráfico peatonal.',
    driveLinks: '',
    referral: '',
    companions: '',
    status: ActivityStatus.COMPLETED,
    location: defaultLocation,
    type: ActivityType.COMMUNITY_VISIT,
    verificationPhoto: 'https://picsum.photos/seed/work1/400/300'
  }
];
